name: Auto Deploy to EC2 on Commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to EC2 and run deploy script
      uses: appleboy/ssh-action@master
      with:
        host: 3.89.244.10
        username: ubuntu
        key: ${{ secrets.githubaction }}
        script: |
          cd /home/ubuntu
          chmod +x deploy.sh
          ./deploy.sh
